server:
  port: 8888
spring:
  application:
    name: config-server
      
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LokeshT3/pre-engagement.git
          search-paths:          
          - main